[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/word.json"
  [headers.values]
    Cache-Control = "public, max-age=30"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
